# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lixin/eric4/GroundStation_eric4/main.ui'
#
# Created: Tue Jun 16 14:04:06 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1162, 736)
        self.gridLayout_10 = QtGui.QGridLayout(Form)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 216))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.mode_lock_check = QtGui.QCheckBox(self.groupBox)
        self.mode_lock_check.setObjectName(_fromUtf8("mode_lock_check"))
        self.horizontalLayout_4.addWidget(self.mode_lock_check)
        self.channel_lock_check = QtGui.QCheckBox(self.groupBox)
        self.channel_lock_check.setObjectName(_fromUtf8("channel_lock_check"))
        self.horizontalLayout_4.addWidget(self.channel_lock_check)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_throto = QtGui.QLabel(self.groupBox)
        self.label_throto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_throto.setObjectName(_fromUtf8("label_throto"))
        self.verticalLayout_3.addWidget(self.label_throto)
        self.slider_throto = QtGui.QSlider(self.groupBox)
        self.slider_throto.setMinimum(1100)
        self.slider_throto.setMaximum(1900)
        self.slider_throto.setSingleStep(25)
        self.slider_throto.setPageStep(25)
        self.slider_throto.setOrientation(QtCore.Qt.Vertical)
        self.slider_throto.setObjectName(_fromUtf8("slider_throto"))
        self.verticalLayout_3.addWidget(self.slider_throto)
        self.label1 = QtGui.QLabel(self.groupBox)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.verticalLayout_3.addWidget(self.label1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_roll = QtGui.QLabel(self.groupBox)
        self.label_roll.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roll.setObjectName(_fromUtf8("label_roll"))
        self.verticalLayout_4.addWidget(self.label_roll)
        self.slider_roll = QtGui.QSlider(self.groupBox)
        self.slider_roll.setMinimum(1100)
        self.slider_roll.setMaximum(1900)
        self.slider_roll.setSingleStep(25)
        self.slider_roll.setPageStep(25)
        self.slider_roll.setProperty("value", 1500)
        self.slider_roll.setOrientation(QtCore.Qt.Vertical)
        self.slider_roll.setObjectName(_fromUtf8("slider_roll"))
        self.verticalLayout_4.addWidget(self.slider_roll)
        self.label2 = QtGui.QLabel(self.groupBox)
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.verticalLayout_4.addWidget(self.label2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_pitch = QtGui.QLabel(self.groupBox)
        self.label_pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitch.setObjectName(_fromUtf8("label_pitch"))
        self.verticalLayout_5.addWidget(self.label_pitch)
        self.slider_pitch = QtGui.QSlider(self.groupBox)
        self.slider_pitch.setMinimum(1100)
        self.slider_pitch.setMaximum(1900)
        self.slider_pitch.setSingleStep(25)
        self.slider_pitch.setPageStep(25)
        self.slider_pitch.setProperty("value", 1500)
        self.slider_pitch.setOrientation(QtCore.Qt.Vertical)
        self.slider_pitch.setObjectName(_fromUtf8("slider_pitch"))
        self.verticalLayout_5.addWidget(self.slider_pitch)
        self.label3 = QtGui.QLabel(self.groupBox)
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.verticalLayout_5.addWidget(self.label3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_yaw = QtGui.QLabel(self.groupBox)
        self.label_yaw.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yaw.setObjectName(_fromUtf8("label_yaw"))
        self.verticalLayout_6.addWidget(self.label_yaw)
        self.slider_yaw = QtGui.QSlider(self.groupBox)
        self.slider_yaw.setMinimum(1100)
        self.slider_yaw.setMaximum(1900)
        self.slider_yaw.setSingleStep(25)
        self.slider_yaw.setPageStep(25)
        self.slider_yaw.setProperty("value", 1500)
        self.slider_yaw.setOrientation(QtCore.Qt.Vertical)
        self.slider_yaw.setObjectName(_fromUtf8("slider_yaw"))
        self.verticalLayout_6.addWidget(self.slider_yaw)
        self.label4 = QtGui.QLabel(self.groupBox)
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName(_fromUtf8("label4"))
        self.verticalLayout_6.addWidget(self.label4)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton_stablize = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_stablize.setFont(font)
        self.radioButton_stablize.setChecked(True)
        self.radioButton_stablize.setObjectName(_fromUtf8("radioButton_stablize"))
        self.verticalLayout.addWidget(self.radioButton_stablize)
        self.radioButton_altitude = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_altitude.setFont(font)
        self.radioButton_altitude.setObjectName(_fromUtf8("radioButton_altitude"))
        self.verticalLayout.addWidget(self.radioButton_altitude)
        self.radioButton_loiter = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_loiter.setFont(font)
        self.radioButton_loiter.setObjectName(_fromUtf8("radioButton_loiter"))
        self.verticalLayout.addWidget(self.radioButton_loiter)
        self.radioButton_auto = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_auto.setFont(font)
        self.radioButton_auto.setObjectName(_fromUtf8("radioButton_auto"))
        self.verticalLayout.addWidget(self.radioButton_auto)
        self.radioButton_land = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_land.setFont(font)
        self.radioButton_land.setObjectName(_fromUtf8("radioButton_land"))
        self.verticalLayout.addWidget(self.radioButton_land)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_21 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem1, 11, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_7.addWidget(self.label_24, 0, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_7.addWidget(self.label_25, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_3)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_7.addWidget(self.label_31, 0, 2, 1, 1)
        self.label_altitude = QtGui.QLabel(self.groupBox_3)
        self.label_altitude.setAlignment(QtCore.Qt.AlignCenter)
        self.label_altitude.setObjectName(_fromUtf8("label_altitude"))
        self.gridLayout_7.addWidget(self.label_altitude, 1, 0, 1, 1)
        self.label_climb_speed = QtGui.QLabel(self.groupBox_3)
        self.label_climb_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_climb_speed.setObjectName(_fromUtf8("label_climb_speed"))
        self.gridLayout_7.addWidget(self.label_climb_speed, 1, 1, 1, 1)
        self.label_ground_speed = QtGui.QLabel(self.groupBox_3)
        self.label_ground_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ground_speed.setObjectName(_fromUtf8("label_ground_speed"))
        self.gridLayout_7.addWidget(self.label_ground_speed, 1, 2, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_7, 21, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_motor1 = QtGui.QLabel(self.groupBox_3)
        self.label_motor1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor1.setObjectName(_fromUtf8("label_motor1"))
        self.gridLayout_9.addWidget(self.label_motor1, 1, 0, 1, 1)
        self.label_motor4 = QtGui.QLabel(self.groupBox_3)
        self.label_motor4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor4.setObjectName(_fromUtf8("label_motor4"))
        self.gridLayout_9.addWidget(self.label_motor4, 1, 3, 1, 1)
        self.label_motor2 = QtGui.QLabel(self.groupBox_3)
        self.label_motor2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor2.setObjectName(_fromUtf8("label_motor2"))
        self.gridLayout_9.addWidget(self.label_motor2, 1, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_3)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_9.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_motor3 = QtGui.QLabel(self.groupBox_3)
        self.label_motor3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor3.setObjectName(_fromUtf8("label_motor3"))
        self.gridLayout_9.addWidget(self.label_motor3, 1, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_3)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_9.addWidget(self.label_30, 0, 3, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_3)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_9.addWidget(self.label_28, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_3)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_9.addWidget(self.label_29, 0, 2, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_9, 10, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem2, 9, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 0, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_3)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 0, 3, 1, 1)
        self.label_channel1 = QtGui.QLabel(self.groupBox_3)
        self.label_channel1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel1.setObjectName(_fromUtf8("label_channel1"))
        self.gridLayout_4.addWidget(self.label_channel1, 1, 0, 1, 1)
        self.label_channel2 = QtGui.QLabel(self.groupBox_3)
        self.label_channel2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel2.setObjectName(_fromUtf8("label_channel2"))
        self.gridLayout_4.addWidget(self.label_channel2, 1, 1, 1, 1)
        self.label_channel3 = QtGui.QLabel(self.groupBox_3)
        self.label_channel3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel3.setObjectName(_fromUtf8("label_channel3"))
        self.gridLayout_4.addWidget(self.label_channel3, 1, 2, 1, 1)
        self.label_channel4 = QtGui.QLabel(self.groupBox_3)
        self.label_channel4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel4.setObjectName(_fromUtf8("label_channel4"))
        self.gridLayout_4.addWidget(self.label_channel4, 1, 3, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_4, 8, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem4, 13, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem5, 20, 0, 1, 1)
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_57 = QtGui.QLabel(self.groupBox_3)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_20.addWidget(self.label_57, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_58 = QtGui.QLabel(self.groupBox_3)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_20.addWidget(self.label_58, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_59 = QtGui.QLabel(self.groupBox_3)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_20.addWidget(self.label_59, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_rollspeed = QtGui.QLabel(self.groupBox_3)
        self.label_rollspeed.setObjectName(_fromUtf8("label_rollspeed"))
        self.gridLayout_20.addWidget(self.label_rollspeed, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_pitchspeed = QtGui.QLabel(self.groupBox_3)
        self.label_pitchspeed.setObjectName(_fromUtf8("label_pitchspeed"))
        self.gridLayout_20.addWidget(self.label_pitchspeed, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_yawspeed = QtGui.QLabel(self.groupBox_3)
        self.label_yawspeed.setObjectName(_fromUtf8("label_yawspeed"))
        self.gridLayout_20.addWidget(self.label_yawspeed, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_21.addLayout(self.gridLayout_20, 19, 0, 1, 1)
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_head_N = QtGui.QLabel(self.groupBox_3)
        self.label_head_N.setAlignment(QtCore.Qt.AlignCenter)
        self.label_head_N.setObjectName(_fromUtf8("label_head_N"))
        self.gridLayout_19.addWidget(self.label_head_N, 1, 1, 1, 1)
        self.label_56 = QtGui.QLabel(self.groupBox_3)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_19.addWidget(self.label_56, 0, 2, 1, 1)
        self.label_55 = QtGui.QLabel(self.groupBox_3)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_19.addWidget(self.label_55, 0, 1, 1, 1)
        self.label_53 = QtGui.QLabel(self.groupBox_3)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_19.addWidget(self.label_53, 0, 0, 1, 1)
        self.label_satellites = QtGui.QLabel(self.groupBox_3)
        self.label_satellites.setAlignment(QtCore.Qt.AlignCenter)
        self.label_satellites.setObjectName(_fromUtf8("label_satellites"))
        self.gridLayout_19.addWidget(self.label_satellites, 1, 2, 1, 1)
        self.label_arm = QtGui.QLabel(self.groupBox_3)
        self.label_arm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_arm.setObjectName(_fromUtf8("label_arm"))
        self.gridLayout_19.addWidget(self.label_arm, 1, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_6.addWidget(self.label_21, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_6.addWidget(self.label_22, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_6.addWidget(self.label_23, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_vol_remain = QtGui.QLabel(self.groupBox_3)
        self.label_vol_remain.setObjectName(_fromUtf8("label_vol_remain"))
        self.gridLayout_6.addWidget(self.label_vol_remain, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_cur_remain = QtGui.QLabel(self.groupBox_3)
        self.label_cur_remain.setObjectName(_fromUtf8("label_cur_remain"))
        self.gridLayout_6.addWidget(self.label_cur_remain, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_bat_remain = QtGui.QLabel(self.groupBox_3)
        self.label_bat_remain.setObjectName(_fromUtf8("label_bat_remain"))
        self.gridLayout_6.addWidget(self.label_bat_remain, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_21.addLayout(self.gridLayout_6, 12, 0, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_11.addWidget(self.label_3, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_11.addWidget(self.label, 0, 0, 1, 1)
        self.label_roll_angle = QtGui.QLabel(self.groupBox_3)
        self.label_roll_angle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_roll_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roll_angle.setObjectName(_fromUtf8("label_roll_angle"))
        self.gridLayout_11.addWidget(self.label_roll_angle, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_11.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_pitch_angle = QtGui.QLabel(self.groupBox_3)
        self.label_pitch_angle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_pitch_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitch_angle.setObjectName(_fromUtf8("label_pitch_angle"))
        self.gridLayout_11.addWidget(self.label_pitch_angle, 1, 1, 1, 1)
        self.label_yaw_angle = QtGui.QLabel(self.groupBox_3)
        self.label_yaw_angle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_yaw_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yaw_angle.setObjectName(_fromUtf8("label_yaw_angle"))
        self.gridLayout_11.addWidget(self.label_yaw_angle, 1, 2, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_11, 14, 0, 5, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem6, 7, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 0, 2, 1, 1)
        self.label_eph = QtGui.QLabel(self.groupBox_3)
        self.label_eph.setAlignment(QtCore.Qt.AlignCenter)
        self.label_eph.setObjectName(_fromUtf8("label_eph"))
        self.gridLayout_5.addWidget(self.label_eph, 0, 3, 1, 1)
        self.label_X_acc = QtGui.QLabel(self.groupBox_3)
        self.label_X_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X_acc.setObjectName(_fromUtf8("label_X_acc"))
        self.gridLayout_5.addWidget(self.label_X_acc, 1, 0, 1, 1)
        self.label_Y_acc = QtGui.QLabel(self.groupBox_3)
        self.label_Y_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y_acc.setObjectName(_fromUtf8("label_Y_acc"))
        self.gridLayout_5.addWidget(self.label_Y_acc, 1, 1, 1, 1)
        self.label_Z_acc = QtGui.QLabel(self.groupBox_3)
        self.label_Z_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z_acc.setObjectName(_fromUtf8("label_Z_acc"))
        self.gridLayout_5.addWidget(self.label_Z_acc, 1, 2, 1, 1)
        self.label_GPS_eph = QtGui.QLabel(self.groupBox_3)
        self.label_GPS_eph.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPS_eph.setObjectName(_fromUtf8("label_GPS_eph"))
        self.gridLayout_5.addWidget(self.label_GPS_eph, 1, 3, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_5, 6, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_GPS_lon = QtGui.QLabel(self.groupBox_3)
        self.label_GPS_lon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPS_lon.setObjectName(_fromUtf8("label_GPS_lon"))
        self.gridLayout_3.addWidget(self.label_GPS_lon, 1, 1, 1, 1)
        self.label_GPS_lat = QtGui.QLabel(self.groupBox_3)
        self.label_GPS_lat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPS_lat.setObjectName(_fromUtf8("label_GPS_lat"))
        self.gridLayout_3.addWidget(self.label_GPS_lat, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.video_3 = QtGui.QTabWidget(self.groupBox_2)
        self.video_3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_3.sizePolicy().hasHeightForWidth())
        self.video_3.setSizePolicy(sizePolicy)
        self.video_3.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.video_3.setStyleSheet(_fromUtf8("border-image: url(:/newPrefix/images/test_map.jpg);"))
        self.video_3.setObjectName(_fromUtf8("video_3"))
        self.map = QtGui.QWidget()
        self.map.setObjectName(_fromUtf8("map"))
        self.video_3.addTab(self.map, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.video_3)
        self.ultrasonic = QtGui.QTabWidget(self.groupBox_2)
        self.ultrasonic.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ultrasonic.sizePolicy().hasHeightForWidth())
        self.ultrasonic.setSizePolicy(sizePolicy)
        self.ultrasonic.setMinimumSize(QtCore.QSize(250, 0))
        self.ultrasonic.setMaximumSize(QtCore.QSize(250, 16777215))
        self.ultrasonic.setObjectName(_fromUtf8("ultrasonic"))
        self.video_2 = QtGui.QWidget()
        self.video_2.setObjectName(_fromUtf8("video_2"))
        self.ultrasonic.addTab(self.video_2, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.ultrasonic)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 11, 1, 1)
        self.pushButton_joystick = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_joystick.setObjectName(_fromUtf8("pushButton_joystick"))
        self.gridLayout_2.addWidget(self.pushButton_joystick, 1, 13, 1, 1)
        self.textBrowser = QtGui.QTextBrowser(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 14)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_2.addWidget(self.label_15)
        self.lineEdit_start = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_start.setObjectName(_fromUtf8("lineEdit_start"))
        self.horizontalLayout_2.addWidget(self.lineEdit_start)
        self.lineEdit_start2 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_start2.setObjectName(_fromUtf8("lineEdit_start2"))
        self.horizontalLayout_2.addWidget(self.lineEdit_start2)
        spacerItem8 = QtGui.QSpacerItem(13, 52, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_2.addWidget(self.label_16)
        self.lineEdit_end = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_end.setObjectName(_fromUtf8("lineEdit_end"))
        self.horizontalLayout_2.addWidget(self.lineEdit_end)
        self.lineEdit_end2 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_end2.setObjectName(_fromUtf8("lineEdit_end2"))
        self.horizontalLayout_2.addWidget(self.lineEdit_end2)
        self.pushButton_Ok = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_Ok.setObjectName(_fromUtf8("pushButton_Ok"))
        self.horizontalLayout_2.addWidget(self.pushButton_Ok)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 14)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_longtitude = QtGui.QLabel(self.groupBox_4)
        self.label_longtitude.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_longtitude.sizePolicy().hasHeightForWidth())
        self.label_longtitude.setSizePolicy(sizePolicy)
        self.label_longtitude.setMaximumSize(QtCore.QSize(350, 16777215))
        self.label_longtitude.setObjectName(_fromUtf8("label_longtitude"))
        self.gridLayout_8.addWidget(self.label_longtitude, 0, 0, 1, 1)
        self.label_latitude = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_latitude.sizePolicy().hasHeightForWidth())
        self.label_latitude.setSizePolicy(sizePolicy)
        self.label_latitude.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_latitude.setObjectName(_fromUtf8("label_latitude"))
        self.gridLayout_8.addWidget(self.label_latitude, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_8, 3, 0, 1, 9)
        self.pushButton_connect = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.gridLayout_2.addWidget(self.pushButton_connect, 1, 2, 1, 1)
        self.pushButton_level = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_level.setObjectName(_fromUtf8("pushButton_level"))
        self.gridLayout_2.addWidget(self.pushButton_level, 1, 3, 1, 1)
        self.pushButton_takeoff = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_takeoff.setObjectName(_fromUtf8("pushButton_takeoff"))
        self.gridLayout_2.addWidget(self.pushButton_takeoff, 1, 7, 1, 1)
        self.pushButton_disarm = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_disarm.setObjectName(_fromUtf8("pushButton_disarm"))
        self.gridLayout_2.addWidget(self.pushButton_disarm, 1, 5, 1, 1)
        self.pushButton_land = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_land.setObjectName(_fromUtf8("pushButton_land"))
        self.gridLayout_2.addWidget(self.pushButton_land, 1, 8, 1, 1)
        self.pushButton_reset = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_reset.setObjectName(_fromUtf8("pushButton_reset"))
        self.gridLayout_2.addWidget(self.pushButton_reset, 1, 9, 1, 1)
        self.pushButton_CV = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_CV.setObjectName(_fromUtf8("pushButton_CV"))
        self.gridLayout_2.addWidget(self.pushButton_CV, 1, 12, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.gridLayout_10.addWidget(self.splitter_2, 0, 1, 1, 1)

        self.retranslateUi(Form)
        self.video_3.setCurrentIndex(0)
        self.ultrasonic.setCurrentIndex(0)
        QtCore.QObject.connect(self.slider_yaw, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_yaw.setNum)
        QtCore.QObject.connect(self.slider_pitch, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_pitch.setNum)
        QtCore.QObject.connect(self.slider_roll, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_roll.setNum)
        QtCore.QObject.connect(self.slider_throto, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_throto.setNum)
        QtCore.QObject.connect(self.mode_lock_check, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.slider_throto.setDisabled)
        QtCore.QObject.connect(self.mode_lock_check, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.slider_roll.setDisabled)
        QtCore.QObject.connect(self.mode_lock_check, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.slider_pitch.setDisabled)
        QtCore.QObject.connect(self.mode_lock_check, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.slider_yaw.setDisabled)
        QtCore.QObject.connect(self.channel_lock_check, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.radioButton_stablize.setDisabled)
        QtCore.QObject.connect(self.channel_lock_check, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.radioButton_altitude.setDisabled)
        QtCore.QObject.connect(self.channel_lock_check, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.radioButton_loiter.setDisabled)
        QtCore.QObject.connect(self.channel_lock_check, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.radioButton_auto.setDisabled)
        QtCore.QObject.connect(self.channel_lock_check, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.radioButton_land.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "GroundStation", None))
        self.groupBox.setTitle(_translate("Form", "   Remote Control", None))
        self.mode_lock_check.setText(_translate("Form", "Lock_channel", None))
        self.channel_lock_check.setText(_translate("Form", "Lock_mode", None))
        self.label_throto.setText(_translate("Form", "1100", None))
        self.label1.setText(_translate("Form", "throttle", None))
        self.label_roll.setText(_translate("Form", "1500", None))
        self.label2.setText(_translate("Form", "  roll    ", None))
        self.label_pitch.setText(_translate("Form", "1500", None))
        self.label3.setText(_translate("Form", " pitch ", None))
        self.label_yaw.setText(_translate("Form", "1500", None))
        self.label4.setText(_translate("Form", " yaw   ", None))
        self.radioButton_stablize.setText(_translate("Form", "stablize", None))
        self.radioButton_altitude.setText(_translate("Form", "altitude", None))
        self.radioButton_loiter.setText(_translate("Form", "loiter", None))
        self.radioButton_auto.setText(_translate("Form", "auto", None))
        self.radioButton_land.setText(_translate("Form", "land", None))
        self.groupBox_3.setTitle(_translate("Form", "   Parameter Display", None))
        self.label_24.setText(_translate("Form", "altitude", None))
        self.label_25.setText(_translate("Form", "climb_speed", None))
        self.label_31.setText(_translate("Form", "ground_speed", None))
        self.label_altitude.setText(_translate("Form", "0m", None))
        self.label_climb_speed.setText(_translate("Form", "0cm/s", None))
        self.label_ground_speed.setText(_translate("Form", "0cm/s", None))
        self.label_motor1.setText(_translate("Form", "0", None))
        self.label_motor4.setText(_translate("Form", "0", None))
        self.label_motor2.setText(_translate("Form", "0", None))
        self.label_27.setText(_translate("Form", "motor1", None))
        self.label_motor3.setText(_translate("Form", "0", None))
        self.label_30.setText(_translate("Form", "motor4", None))
        self.label_28.setText(_translate("Form", "motor2", None))
        self.label_29.setText(_translate("Form", "motor3", None))
        self.label_12.setText(_translate("Form", "channel 1", None))
        self.label_13.setText(_translate("Form", "channel 2", None))
        self.label_14.setText(_translate("Form", "channel 3", None))
        self.label_26.setText(_translate("Form", "channel 4", None))
        self.label_channel1.setText(_translate("Form", "0", None))
        self.label_channel2.setText(_translate("Form", "0", None))
        self.label_channel3.setText(_translate("Form", "0", None))
        self.label_channel4.setText(_translate("Form", "0", None))
        self.label_57.setText(_translate("Form", "rollspeed", None))
        self.label_58.setText(_translate("Form", "pitchspeed", None))
        self.label_59.setText(_translate("Form", "yawspeed", None))
        self.label_rollspeed.setText(_translate("Form", "0", None))
        self.label_pitchspeed.setText(_translate("Form", "0", None))
        self.label_yawspeed.setText(_translate("Form", "0", None))
        self.label_head_N.setText(_translate("Form", "0", None))
        self.label_56.setText(_translate("Form", "satellites", None))
        self.label_55.setText(_translate("Form", "head_N", None))
        self.label_53.setText(_translate("Form", "arm", None))
        self.label_satellites.setText(_translate("Form", "0", None))
        self.label_arm.setText(_translate("Form", "0", None))
        self.label_21.setText(_translate("Form", "vol_remain", None))
        self.label_22.setText(_translate("Form", "cur_remain", None))
        self.label_23.setText(_translate("Form", "bat_remain", None))
        self.label_vol_remain.setText(_translate("Form", "0mV", None))
        self.label_cur_remain.setText(_translate("Form", "0mA", None))
        self.label_bat_remain.setText(_translate("Form", "0%", None))
        self.label_3.setText(_translate("Form", "pitch_angle", None))
        self.label.setText(_translate("Form", "roll_angle", None))
        self.label_roll_angle.setText(_translate("Form", "0rad", None))
        self.label_4.setText(_translate("Form", "yaw_angle", None))
        self.label_pitch_angle.setText(_translate("Form", "0rad", None))
        self.label_yaw_angle.setText(_translate("Form", "0rad", None))
        self.label_17.setText(_translate("Form", "X_acc", None))
        self.label_18.setText(_translate("Form", "Y_acc", None))
        self.label_19.setText(_translate("Form", "Z_acc", None))
        self.label_eph.setText(_translate("Form", "GPS_eph", None))
        self.label_X_acc.setText(_translate("Form", "0", None))
        self.label_Y_acc.setText(_translate("Form", "0", None))
        self.label_Z_acc.setText(_translate("Form", "0", None))
        self.label_GPS_eph.setText(_translate("Form", "0", None))
        self.label_GPS_lon.setText(_translate("Form", "0", None))
        self.label_GPS_lat.setText(_translate("Form", "0", None))
        self.label_10.setText(_translate("Form", "GPS_lon", None))
        self.label_11.setText(_translate("Form", "GPS_lat", None))
        self.video_3.setTabText(self.video_3.indexOf(self.map), _translate("Form", "map", None))
        self.ultrasonic.setTabText(self.ultrasonic.indexOf(self.video_2), _translate("Form", "Ultrasonic ranging", None))
        self.groupBox_4.setTitle(_translate("Form", "Status", None))
        self.pushButton_joystick.setText(_translate("Form", "joystick", None))
        self.label_15.setText(_translate("Form", "起点：", None))
        self.label_16.setText(_translate("Form", "终点：", None))
        self.pushButton_Ok.setText(_translate("Form", "OK", None))
        self.label_longtitude.setText(_translate("Form", "经度跨度：                                                      ", None))
        self.label_latitude.setText(_translate("Form", "纬度跨度：              ", None))
        self.pushButton_connect.setText(_translate("Form", "connect", None))
        self.pushButton_level.setText(_translate("Form", "level", None))
        self.pushButton_takeoff.setText(_translate("Form", "take off", None))
        self.pushButton_disarm.setText(_translate("Form", "disarm", None))
        self.pushButton_land.setText(_translate("Form", "land", None))
        self.pushButton_reset.setText(_translate("Form", "reset", None))
        self.pushButton_CV.setText(_translate("Form", "CV", None))

import pics_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

